name: Publish Docker image

on:
  push:
    branches:
      - 'develop'
    tags:
      - 'v*.*.*'

jobs:
  push_to_registry:
    name: Build docker image and push it to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Docker Build environment
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
          
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pagermon/pagermon
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: server/Dockerfile
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  push_to_registry_armhf:
    name: Build ARMv7 Docker image and push it to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
        
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@5
        with:
          images: pagermon/pagermon
      
      - name: Build and push Docker image - ARMHF
        uses: docker/build-push-action@v5
        with:
          file: server/Dockerfile.armhf
          context: ./server
          platforms: linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}-armhf
          cache-from: type=gha
          cache-to: type=gha,mode=max
